# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotular < Formula
  desc "A config-driven dotfile manager"
  homepage "https://github.com/atomikpanda/dotular"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atomikpanda/dotular/releases/download/v0.1.0/dotular_0.1.0_darwin_amd64.tar.gz"
      sha256 "b6455d0b2fe350d5094310c54628c6a106de1de18f00e68419e9a9a9f6c30a96"

      define_method(:install) do
        bin.install "dotular"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atomikpanda/dotular/releases/download/v0.1.0/dotular_0.1.0_darwin_arm64.tar.gz"
      sha256 "d0c72bb8639b9a462d79b1af7131bd80ff873db746c1293474df3cdf453d8233"

      define_method(:install) do
        bin.install "dotular"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomikpanda/dotular/releases/download/v0.1.0/dotular_0.1.0_linux_amd64.tar.gz"
      sha256 "189c40616fbea8f111754e64206b55c341d35dd5fdbe4d34b0559aea8897951a"
      define_method(:install) do
        bin.install "dotular"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomikpanda/dotular/releases/download/v0.1.0/dotular_0.1.0_linux_arm64.tar.gz"
      sha256 "77b27430be98382d4a638c70dd8536d81b15c5bbacc7fdd9a6875ffa85b49f5a"
      define_method(:install) do
        bin.install "dotular"
      end
    end
  end

  test do
    system "#{bin}/dotular", "platform"
  end
end
